name: Firebase hosting deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM install and build
        run: npm ci && CI=false npm run build

      - name: Jest testing
        run: npm run test

      - name: Firebase deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTHENTICATION_CICD }}"
          channelId: live
          projectId: authentication-cicd
